### PR TITLE
Fix build with libnfc-nxp

### PR DESCRIPTION
**Pull request by neochapay**

### CODE REVIEW

**Comment by andi34** [comment]
Please submit patches on Gerrit for review, we don't merge pull request on GH. Thanks for your contribution.

https://gerrit.unlegacy-android.org

**Comment by neochapay** [comment]
yea....so user friendly....

**Comment by airend** [comment]
> yea....so user friendly....

I think you're misunderstanding the previous message. Contributions are very much welcome, but you should explain what you're trying to fix. If Gerrit is not an option for you, and depending on your changes, one of us can push it for review. But you need to describe the need for your changes.

**Comment by neochapay** [comment]
@airend i update my PR 

I just whant build Unlegalecy Android 8.1 for Nexus 7 (2012) 3G aaaaaaaaand:

image

**Pull request closed without merging**
